CREATE TABLE IF NOT EXISTS DATAEXPERT_STUDENT.BRYAN.raw_workout (
    id                      VARCHAR,
    v1_id                   VARCHAR,
    user_id                 VARCHAR,
    created_at              TIMESTAMP_NTZ,
    updated_at              TIMESTAMP_NTZ,
    start_time              TIMESTAMP_NTZ,
    end_time                TIMESTAMP_NTZ,
    timezone_offset         VARCHAR,
    sport_name              VARCHAR,
    score_state             VARCHAR,
    sport_id                INTEGER,
    strain                  FLOAT,
    average_heart_rate      INTEGER,
    max_heart_rate          INTEGER,
    kilojoule               FLOAT,
    percent_recorded        FLOAT,
    distance_meter          FLOAT,
    altitude_gain_meter     FLOAT,
    altitude_change_meter   FLOAT,
    zone_zero_milli         INTEGER,
    zone_one_milli          INTEGER,
    zone_two_milli          INTEGER,
    zone_three_milli        INTEGER,
    zone_four_milli         INTEGER,
    zone_five_milli         INTEGER,
    ingested_at             TIMESTAMP_NTZ
);
